"""added is_active in todo

Revision ID: 9a246a5786bc
Revises: 6d815eaf6331
Create Date: 2025-02-02 00:16:38.426029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a246a5786bc'
down_revision: Union[str, None] = '6d815eaf6331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_active')
    # ### end Alembic commands ###
